[tool.poetry]
authors = ["AllenChou <f1470891079@gmail.com>"]
description = "Execute function with FastAPI features."
license = "MIT"
name = "fastexec"
readme = "README.md"
version = "0.6.0"

[tool.poetry.dependencies]
fastapi = { extras = ["standard"], version = ">=0.121.0,<1.0.0" }
python = ">=3.11,<4.0"

[tool.poetry.extras]
all = []

[tool.poetry.group.dev.dependencies]
black = { extras = ["jupyter"], version = "*" }
faker = "*"
isort = "*"
networkx = "*"
plotly = "*"
poetry-plugin-export = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-xdist = "*"
pyvis = "*"
setuptools = ">=69"

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["E203", "E704", "W503"]
max-line-length = 88

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
